# Generated by Django 3.0.3 on 2020-02-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
