# Generated by Django 3.0.3 on 2020-02-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travello', '0002_remove_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
